var nome = prompt ('Ciao, come ti chiami?');
console.log('Il suo nome é ' + nome);
var cognome = prompt("Ciao " + nome + ", qual'è il tuo cognome?");
console.log('Il suo cognome é ' + cognome);
var colore = prompt("Qual'é il tuo clore preferito?");
console.log("il suo colore preferito è " + colore);
var container = document.getElementById('password');
var anno = new Date().getFullYear();
container.innerText = ('Ciao la tua password é: ');
container.append('\n' + nome + cognome + colore + anno);
